"""The HTML report must not execute text that came from the batch or the model.

The report is the artifact a reviewer opens in a browser, and two of the strings
it renders are not written by this codebase: `case_id`, which arrives in the
batch file, and the classifier's `rationale`, which is free text generated by a
language model and stamped into the audit event's `detail` field
(`engine.py:282`). Both reach the page. Every interpolation is wrapped in
`_esc()` today, but that is a convention held up by whoever last edited a
template string, so these tests hold it up instead.

Each test asserts two things, and the second matters more: that the payload does
not appear raw, and that its escaped form *does* appear. Without the second
assertion the test passes just as happily when the field stops being rendered at
all, which would make it a guard over nothing.
"""

from __future__ import annotations

from pathlib import Path

from helpers import build_run
from reclaim.config import AppConfig
from reclaim.models import FailedTransaction, RootCause
from reclaim.report import build_report

# A payload that breaks out of both an element body and a `<code>` block, and
# whose `onerror` fires without needing a script tag to be honoured.
PAYLOAD = "<script>alert(1)</script><img src=x onerror=alert(2)>"
ESCAPED = "&lt;script&gt;alert(1)&lt;/script&gt;"


def _assert_inert(html: str) -> None:
    """The payload may appear, but only with its angle brackets neutered.

    Asserting on `onerror=alert(2)` would be the wrong check: that substring
    survives escaping and is inert, because `&lt;img ...&gt;` is text. What must
    never survive is a character sequence a parser can read as a tag.
    """
    assert PAYLOAD not in html
    assert "<script" not in html
    assert "<img" not in html


def _render(config: AppConfig, records: list[FailedTransaction], tmp_path: Path) -> str:
    out = tmp_path / "out"
    result = build_run(config, records, out, tmp_path).execute()
    return build_report(result.run_id, out, config)


def test_a_hostile_case_id_from_the_batch_is_escaped_in_the_report(
    config: AppConfig, batch: list[FailedTransaction], tmp_path: Path
) -> None:
    """`case_id` is batch-controlled and reaches the queue table, the worked
    example, and the replay hint. A batch is untrusted input here."""
    poisoned = [r.model_copy(update={"case_id": f"{r.case_id}{PAYLOAD}"}) for r in batch]
    html = _render(config, poisoned, tmp_path)

    _assert_inert(html)
    assert ESCAPED in html, "case_id no longer reaches the report; this test now guards nothing"


class _HostileLlm:
    """A model that answers correctly and narrates in HTML.

    Not a far-fetched failure: the rationale is unconstrained free text, and the
    decline descriptions it is asked to explain are themselves batch-controlled.
    """

    def __init__(self) -> None:
        self.calls: list[str] = []

    def classify(
        self, decline_code: str, description: str, model: str, max_tokens: int
    ) -> tuple[RootCause, float, str]:
        self.calls.append(decline_code)
        return (RootCause.INSUFFICIENT_FUNDS, 0.95, f"balance too low {PAYLOAD}")


def test_a_hostile_model_rationale_is_escaped_in_the_report(
    config: AppConfig, batch: list[FailedTransaction], tmp_path: Path
) -> None:
    """The rationale lands in the audit `detail`, which the chain section
    renders verbatim."""
    llm = _HostileLlm()
    # Both the code and the description have to miss the rule layer. Leaving the
    # generator's description in place lets a keyword pattern classify the case,
    # the model is never consulted, and the test proves nothing.
    unmapped = [
        r.model_copy(
            update={
                "decline_code": "XX_NOT_IN_ANY_RULE",
                "decline_description": "issuer returned an opaque response",
            }
        )
        for r in batch
    ]
    out = tmp_path / "out"
    result = build_run(config, unmapped, out, tmp_path, llm_client=llm).execute()
    html = build_report(result.run_id, out, config)

    assert llm.calls, "the model layer never ran; this test now guards nothing"
    _assert_inert(html)
    assert ESCAPED in html, "the rationale no longer reaches the report"


def test_the_report_embeds_no_external_reference(
    config: AppConfig, batch: list[FailedTransaction], tmp_path: Path
) -> None:
    """Self-contained is a security property as well as a demo property: a
    report that fetches nothing cannot leak the run it describes by fetching."""
    html = _render(config, batch, tmp_path)
    for scheme in ("http://", "https://", "//cdn", 'src="http'):
        assert scheme not in html
